export const DELETE_NOTIFICATION = {
  REQUEST: 'DELETE_NOTIFICATION_REQUEST',
  SUCCESS: 'DELETE_NOTIFICATION_SUCCESS',
  FAILURE: 'DELETE_NOTIFICATION_FAILURE',
};
export const FETCH_NOTIFICATION = {
  REQUEST: 'FETCH_NOTIFICATION_REQUEST',
  SUCCESS: 'FETCH_NOTIFICATION_SUCCESS',
  FAILURE: 'FETCH_NOTIFICATION_FAILURE',
};
