export const ADD_MENU = {
    REQUEST: 'ADD_MENU_REQUEST',
    SUCCESS: 'ADD_MENU_SUCCESS',
    FAILURE: 'ADD_MENU_FAILURE',
  };
  export const DELETE_MENU = {
    REQUEST: 'DELETE_MENU_REQUEST',
    SUCCESS: 'DELETE_MENU_SUCCESS',
    FAILURE: 'DELETE_MENU_FAILURE',
  };
  export const UPDATE_MENU = {
    REQUEST: 'UPDATE_MENU_REQUEST',
    SUCCESS: 'UPDATE_MENU_SUCCESS',
    FAILURE: 'UPDATE_MENU_FAILURE',
  };
  export const FETCH_MENU = {
    REQUEST: 'FETCH_MENU_REQUEST',
    SUCCESS: 'FETCH_MENU_SUCCESS',
    FAILURE: 'FETCH_MENU_FAILURE',
  };
  