export const ADD_BLOG = {
  REQUEST: 'ADD_BLOG_REQUEST',
  SUCCESS: 'ADD_BLOG_SUCCESS',
  FAILURE: 'ADD_BLOG_FAILURE',
};
export const UPDATE_BLOG = {
  REQUEST: 'UPDATE_BLOG_REQUEST',
  SUCCESS: 'UPDATE_BLOG_SUCCESS',
  FAILURE: 'UPDATE_BLOG_FAILURE',
};
export const DELETE_BLOG = {
  REQUEST: 'DELETE_BLOG_REQUEST',
  SUCCESS: 'DELETE_BLOG_SUCCESS',
  FAILURE: 'DELETE_BLOG_FAILURE',
};
export const FETCH_BLOG = {
  REQUEST: 'FETCH_BLOG_REQUEST',
  SUCCESS: 'FETCH_BLOG_SUCCESS',
  FAILURE: 'FETCH_BLOG_FAILURE',
};
