export const ADD_PRODUCT = {
  REQUEST: 'ADD_PRODUCT_REQUEST',
  SUCCESS: 'ADD_PRODUCT_SUCCESS',
  FAILURE: 'ADD_PRODUCT_FAILURE',
};
export const DELETE_PRODUCT = {
  REQUEST: 'DELETE_PRODUCT_REQUEST',
  SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  FAILURE: 'DELETE_PRODUCT_FAILURE',
};
export const UPDATE_PRODUCT = {
  REQUEST: 'UPDATE_PRODUCT_REQUEST',
  SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  FAILURE: 'UPDATE_PRODUCT_FAILURE',
};
export const FETCH_PRODUCT = {
  REQUEST: 'FETCH_PRODUCT_REQUEST',
  SUCCESS: 'FETCH_PRODUCT_SUCCESS',
  FAILURE: 'FETCH_PRODUCT_FAILURE',
};
