export const ADD_EVENT = {
  REQUEST: 'ADD_EVENT_REQUEST',
  SUCCESS: 'ADD_EVENT_SUCCESS',
  FAILURE: 'ADD_EVENT_FAILURE',
};
export const DELETE_EVENT = {
  REQUEST: 'DELETE_EVENT_REQUEST',
  SUCCESS: 'DELETE_EVENT_SUCCESS',
  FAILURE: 'DELETE_EVENT_FAILURE',
};
export const UPDATE_EVENT = {
  REQUEST: 'UPDATE_EVENT_REQUEST',
  SUCCESS: 'UPDATE_EVENT_SUCCESS',
  FAILURE: 'UPDATE_EVENT_FAILURE',
};
export const FETCH_EVENT = {
  REQUEST: 'FETCH_EVENT_REQUEST',
  SUCCESS: 'FETCH_EVENT_SUCCESS',
  FAILURE: 'FETCH_EVENT_FAILURE',
};
