export const ADD_CATEGORY = {
  REQUEST: 'ADD_CATEGORY_REQUEST',
  SUCCESS: 'ADD_CATEGORY_SUCCESS',
  FAILURE: 'ADD_CATEGORY_FAILURE',
};

export const DELETE_CATEGORY = {
  REQUEST: 'DELETE_CATEGORY_REQUEST',
  SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  FAILURE: 'DELETE_CATEGORY_FAILURE',
};
